### ISSUE TITLE
Dataset opening on last page

### ISSUE THREAD

**Issue by potofcoffee** [kouts/vue-dataset#103]
I have a dataset that is empty on mount. The data is loaded in the parent's mounted() method and arrives whenever the AJAX call there has finished. The dataset does populate correctly, then, but it always opens on the last page. Is there a way to fix this?

**Comment by kouts** [comment]
Here's a demo of that case, the dataset opens on the first page
https://stackblitz.com/edit/vue-rbm9pl?file=src%2FApp.vue

Feel free to re-open this issue when you have a codesandbox or stackblitz replicating the behavior.
