### ISSUE TITLE
How to sum filtered result?

### ISSUE THREAD

**Issue by Pachara** [kouts/vue-dataset#106]
Hi,
I want to sum the filtered result, How to do that?
<img width="923" alt="Screenshot 2566-01-25 at 16 53 56" src="https://user-images.githubusercontent.com/107335/214533503-2e1eaa9d-3d2f-4ad5-9425-a4a1e814700f.png">

**Comment by kouts** [comment]
Hello @Pachara, currently dataset doesn't provide a way of getting the filtered results.

**Comment by kouts** [comment]
There's now an `update:dsData` event that returns the filtered data.
You can use it in order to compute the sum.
@Pachara you can check the example here: https://github.com/kouts/vue-dataset/blob/6a37b323b62bbbc8aa4dbec872b98547c22cadc4/playground/views/Example2.vue#L16
