### ISSUE TITLE
:ds-search-in="['customer.xxxx']" nested object

### ISSUE THREAD

**Issue by grabelle** [kouts/vue-dataset#107]
Hi,
I have a ds-data like 
`[
{
reference:'ref1',
customer:{
    name:'my name1',
    code:'my code1'}
},
reference:'ref2',
customer:{
    name:'my name2',
    code:'my code2'}
}
]`

I added :ds-search-in="['customer.code']" but it doesn't work i search for 'My code2'
Where am I wrong ?

Thanks a lot for your help
Guillaume

**Comment by kouts** [comment]
Hello, @grabelle currently searching through nested objects is not supported.

**Comment by kouts** [comment]
Hello @grabelle, although searching in nested objects is not supported by default, you can achieve what you want by customizing the search function for the field you want to search (in your case `customer`) using the `search-as` prop.
Check this Stackblitz example in which you can search the `favoriteColor` attribute inside the `extra` attribute of the data objects.
https://stackblitz.com/edit/vue-sxre9l?file=src/App.vue

**Comment by clabnet** [comment]
Hello @grabelle , I have the same problem. 
The stackblitz example It seems not working.  
Have you a suggestion for me ? I still using Vue 3 with `next` branch.
