### ISSUE TITLE
documentation: ds-filter-fields

### ISSUE THREAD

**Issue by mg1075** [kouts/vue-dataset#115]
The general functionality of `ds-filter-fields` might benefit from further detail as to how multiple values for one field can be part of the filtering of that field and how testing for the truthiness of a condition is the basis for filtering rather than just passing the actual list of values as the filter (in my mind, the latter would have been a more intuitive and simpler approach for the end-user).

Also, the documentation seems to have a bug related to the explanation. 
```
startsWithD (value) {
  return value.toLowerCase().startsWith('D')
}
```
The `startsWithD` function is going to return `false` all the time because `startsWith('D')` is always comparing a lowercase d with an uppercase D. I think the function was supposed to be `value.toLowerCase().startsWith('d')`?

https://next--vue-dataset-demo.netlify.app/components/#props

**Comment by kouts** [comment]
Thanks @mg1075 this is now fixed with [fbe918a](https://github.com/kouts/vue-dataset/pull/127/commits/fbe918a32fb4f99d47ddb0410c703990a867d575)
