### ISSUE TITLE
documentation: update:dsData and returned data object after filter function

### ISSUE THREAD

**Issue by mg1075** [kouts/vue-dataset#116]
The documentation for `update:dsData` as found on the "next" site left me wondering how to use the feature.
https://next--vue-dataset-demo.netlify.app/components/#provides

Fortunately, someone had raised the issue earlier on github. "What is the returned data object after I run a filter function? #95"
https://github.com/kouts/vue-dataset/issues/95

An example of how to use the api was provided in the answer.
https://github.com/kouts/vue-dataset/blob/6a37b323b62bbbc8aa4dbec872b98547c22cadc4/playground/views/Example2.vue#L16

It would be helpful if the documentation site could reflect some of this info so it is not necessary to search through github issues as to how the `update:dsData` feature works.

**Comment by kouts** [comment]
Thanks for your comments and your interest in `vue-dataset` @mg1075, PRs are welcome!

**Comment by kouts** [comment]
Closing this as the docs now mention that the return of the `update:dsData` is an array of objects.
