### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by aznj** [kouts/vue-dataset#23]
Is Vue 3 support in the roadmap?

**Comment by kouts** [comment]
Hey @aznj, this is something that I would also like to do at some point.
Let's leave this open so that we can see if there's enough interest.

**Comment by wjcroom** [comment]
no scss in the example2.vue
how to config the style file??

**Comment by grandgeorg** [comment]
I'd be quite interested as I'm using Vue 3 with Composition API.

**Comment by kouts** [comment]
Vue 3 support is now on the way

**Comment by kouts** [comment]
Support for Vue 3 is now ready and available through the v2 https://github.com/kouts/vue-dataset/tree/next branch.
The API is exactly the same as v1 with the only difference being that `vue-dataset` now provides reactive data using [refs](https://v3.vuejs.org/api/refs-api.html#refs)

You can install it with `npm install vue-dataset@next`
The docs site for v2 is https://next--vue-dataset-demo.netlify.app/

Have fun using `vue-dataset` with Vue 3 🚀
