### ISSUE TITLE
Comparison Mode "Multiple"

### ISSUE THREAD

**Issue by GuiltyRemnant** [kouts/vue-dataset#35]
Hi there, 

first: very nice extension, thanks for developing.

My question is: is it possible to have a checkbox logic, where the cards in the list get filtered on a multiple comparison mode? 

[ checkbox-a, checkbox-b ]

So, i check checkbox a and the list displays only items with items-a - so far, so good, thats what possible in the cards example - but when i also check checkbox b, i want the list to display items with values a and b. 

So, instead of a radio-logic like in the example, i want a checkbox logic where the items in the list add up based on the selected checkboxes. Any ideas how i get there?

**Comment by kouts** [comment]
Hello @GuiltyRemnant, thanks for the nice words.
You can pass a `function` to the object prop of `ds-filter-fields` to achieve this.
I've prepared a [code sandbox](ds-filter-fields), please tell me if this works for you.

**Comment by GuiltyRemnant** [comment]
Thank you so much for doing that for me :)

I tried to figure this out for me, but i still struggle to implement it for my usecase.
When i try to filter more than one property over the ds-filter-fields, i doesnt work for me.

My json looks like this: https://codesandbox.io/s/vue-dataset-multiple-forked-qlllq?file=/src/users.json

Lets say i want to do a partner portal, where all the cards are showing when i initialy come to the website (i experimented with a method and tried it with updating my users list, but i failed horribly).

When i check the checkbox for "cool_dude", only the cards should showing up, that are "cool_dude": true in the json. When i now check "blue_eyes" checkbox, i want to see all results for "cool_dude" and "blue_eyes". 

What broke my neck on my own experiment was, when i uncheck one of the boxes again, it doesnt deliver the right result anymore (so for example, when i uncheck blue_eyes, it shows results with long legs or so, not the results with cool_dude). 

And when everything is unchecked again, show the full list again - what i did here for me was an array, that remembers the checked filter and when this array is empty, return with an original copy of the users as an result. This piece of code works pretty nice - the other not so much :D

**Comment by kouts** [comment]
What you want is to dynamically construct a filter object and pass it to the `ds-filter-fields`.
It might be a little bit tricky because your JSON contains empty string in case there's a `false ` value but
something like [this will do the trick](https://codesandbox.io/s/vue-dataset-multiple-object-mh90j?file=/src/App.vue)

**Comment by GuiltyRemnant** [comment]
This works like a charme - thank you so much :)
I am a fan now! <3
