### ISSUE TITLE
External contributions

### ISSUE THREAD

**Issue by cberthiaume** [kouts/vue-dataset#39]
@kouts -- Thank you for this useful project. I'm using in a current project and finding it very helpful. There were a few changes I needed to make to suit my needs including using Bootstrap 5, some additional styling items, and a couple bug fixes. I ended up just pulling the code files into my project branch and making local modifications. Along the way, I converted it over to the composition API since that's what I'm using in my project.

I'd love to help your project out if my changes are useful. Unfortunately, it'll be a while before I have time to make a proper PR from a branch of your project. If you'd find it useful I can send you my version of code along with some notes about what I changed.

Either way, thanks for you work on this.

**Comment by brianwachira** [comment]
> Hi, is `vue-dataset` support for serverside ?

wondering the same too

**Comment by kouts** [comment]
`vue-dataset` is created to facilitate the handling of large datasets on the client side.
So there's no support for server-side API communication.
