### ISSUE TITLE
Unable to sort by id or date

### ISSUE THREAD

**Issue by wahyusaragih** [kouts/vue-dataset#46]
I can't sort by id or by date, how can I solve it?
Thank you
![image](https://user-images.githubusercontent.com/51875970/142734361-f9fb6242-2d67-44d3-9e3f-f888538b5b70.png)
![image](https://user-images.githubusercontent.com/51875970/142734378-3f843e23-9516-4806-ae0a-6e811f76366c.png)

**Comment by kouts** [comment]
Hello @wahyusaragih, you can use the [sort-as](https://vue-dataset-demo.netlify.app/components/#ds-sort-as) prop for that.
There's also a relevant example that you can check here:
https://vue-dataset-demo.netlify.app/examples/datatable/

**Comment by wahyusaragih** [comment]
Hey, Sorry my bad, It's a typo mistake and I can sort properly now. Thank you
