### ISSUE TITLE
Why does DatasetShow output DOM?

### ISSUE THREAD

**Issue by chasegiunta** [kouts/vue-dataset#47]
Hi there,

I'm wondering why `dataset-show` outputs
```
<div class="form-inline">
  <label>Show</label>
  <select class="form-control mr-1 ml-1"> ... </select>
  <label>entries</label>
</div>
```
I would think it would solely output the `<select>` and the dev could make the decision on whether they want to output "Show" & "entries", and _where_ to output them, as well as what classes to give them, if any.

Is there a way to remove these or override the classes passed? Currently, this is how the outlook looks:
![image](https://user-images.githubusercontent.com/1377169/144175718-5e4107b8-5509-4c9b-998c-8c7cc788e7fe.png)

**Comment by kouts** [comment]
Hey @chasegiunta, `Dataset` comes with some Bootstrap classes out of the box but you can easily style its components
by passing a custom class and then applying CSS rules.
Something like
```
<template>
  ...
  <dataset-show :ds-show-entries="selected" @changed="selected = $event"  class="my-class" />
  ...
</template>
<style>
.my-class select {
  border: 1px solid purple;  
}
</style>

```
If that doesn't fit your use case though, you can easily copy the [DatasetShow](https://github.com/kouts/vue-dataset/blob/master/src/DatasetShow.vue) code and style it to your liking!

**Comment by chasegiunta** [comment]
Makes sense. Thanks!
