### ISSUE TITLE
Access data sub element 

### ISSUE THREAD

**Issue by yassbeno** [kouts/vue-dataset#58]
Hello, 
the title is a bit vague so let me illustrate : 
i would like to know if  "ds-search-in" can take an element that is inside an object, basically like this :
![image](https://user-images.githubusercontent.com/40161273/147947034-b63b2f68-e87c-4578-bb87-6fda218acd84.png)
![image](https://user-images.githubusercontent.com/40161273/147947075-9534ab59-2ce5-4564-bd51-e16e1ea0688b.png)

Thanks !

**Comment by kouts** [comment]
Hello @yassbeno, unfortunately searching in nested object properties is not supported at the moment, but maybe you can achieve what you want with the `ds-search-as` prop. You can pass in a custom function to search a certain data property.

**Comment by yassbeno** [comment]
> Hello @yassbeno, unfortunately searching in nested object properties is not supported at the moment, but maybe you can achieve what you want with the `ds-search-as` prop. You can pass in a custom function to search a certain data property.

Nested object properties, exactly the words that i couldn't find. Thank you for the answer
