### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by potofcoffee** [kouts/vue-dataset#61]
First of all, thank you for this very useful project! 

I was wondering: How would I go about changing I18N to another language?

**Comment by kouts** [comment]
Hey @potofcoffee, in order to customize the texts of `Dataset` you can create a new `Dataset` component that [extends](https://vuejs.org/v2/api/#extends) the original one and provide the translated texts in its `data` property.
For example:

`myDataset.js`
```
import { Dataset } from 'from 'vue-dataset'

export default {
  extends: Dataset,
  data() {
    return {
      // Provide the translated texts here
      datasetI18n: {
        show: 'Show',
        entries: 'entries',
        previous: 'Previous',
        next: 'Next',
        showing: 'Showing',
        showingTo: 'to',
        showingOf: 'of',
        showingEntries: 'entries'
      }
    }
  }
}
```
Then you can use it like this:
```
 import  MyDataset from './myDataset.js'
```

**Comment by abaumg** [comment]
How could I achieve this with Vue3?
