### ISSUE TITLE
Group results

### ISSUE THREAD

**Issue by potofcoffee** [kouts/vue-dataset#67]
Is there an easy way to group results? E.g., with a dataset like this:
````
    [
         { id: 0, grouptitle: 'Group 1', items: [
             { id: 0, title: 'Test 1' },
             { id: 1, title: 'Test 2' },
        ]},
         { id: 1, grouptitle: 'Group 2', items: [
             { id: 0, title: 'Test 3' },
             { id: 1, title: 'Test 4' },
        ]},
   ]
````

... to create a table something like this:

<table>
<tr><th>ID</th><th>Title</th></tr>
<tr><td colspan="2">Group 1</td></tr>
<tr><td>0</td><td>Test 1</td></tr>
<tr><td>1</td><td>Test 2</td></tr>
<tr><td colspan="2">Group 2</td></tr>
<tr><td>0</td><td>Test 3</td></tr>
<tr><td>1</td><td>Test 4</td></tr>
</table>

**Comment by kouts** [comment]
There's no such feature in `vue-dataset` , maybe you can achieve something like that with a custom `[DatasetItem.vue](https://github.com/kouts/vue-dataset/blob/master/src/DatasetItem.vue)` component but I'm not sure.
