### ISSUE TITLE
search in object

### ISSUE THREAD

**Issue by wahyusaragih** [kouts/vue-dataset#70]
I have a json like this
`
[
  {
    "id": 1,
    "station_name": "ARR Sungsang",
    "station_type": 1,
    "provinsi": 1,
    "balai": 1,
    "location": "Sungsang 1",
    "sungai": null,
    "sn_logger": "1",
    "sn_modem": "1",
    "longitude": 104.897285,
    "latitude": -2.364155,
    "elevasi": 4,
    "image": "/media/stations/e4eb6e30-0a9.jpg",
    "topic_MQTT": "topic 1",
    "observator": "obs arr 1",
    "observator_phone": "0897887887",
    "map_icon": 1,
    "siaga": 1
  },
  {
    "sensor1_act": true,
    "sensor1_ch": 1,
    "sensor1_w_lvl_1": 1,
    "sensor1_w_lvl_2": 1.5,
    "sensor1_w_lvl_3": 2,
  }
]
`
How to search inside station_name? thanks

**Comment by kouts** [comment]
Hello @wahyusaragih, `vue-dataset` can search inside an array of objects given that all objects contain the same keys.
So in your case you'll have to merge all the data into one object for example like this:
```
const data = [
  {
    id: 1,
    station_name: 'ARR Sungsang',
    station_type: 1,
    provinsi: 1,
    balai: 1,
    location: 'Sungsang 1',
    sungai: null,
    sn_logger: '1',
    sn_modem: '1',
    longitude: 104.897285,
    latitude: -2.364155,
    elevasi: 4,
    image: '/media/stations/e4eb6e30-0a9.jpg',
    topic_MQTT: 'topic 1',
    observator: 'obs arr 1',
    observator_phone: '0897887887',
    map_icon: 1,
    siaga: 1,
    sensor1_act: true,
    sensor1_ch: 1,
    sensor1_w_lvl_1: 1,
    sensor1_w_lvl_2: 1.5,
    sensor1_w_lvl_3: 2
  },
  {
    id: 2,
    station_name: 'Station 2',
    station_type: 1,
    provinsi: 1,
    balai: 1,
    location: 'Sungsang 1',
    sungai: null,
    sn_logger: '1',
    sn_modem: '1',
    longitude: 104.897285,
    latitude: -2.364155,
    elevasi: 4,
    image: '/media/stations/e4eb6e30-0a9.jpg',
    topic_MQTT: 'topic 1',
    observator: 'obs arr 1',
    observator_phone: '0897887887',
    map_icon: 1,
    siaga: 1,
    sensor1_act: true,
    sensor1_ch: 1,
    sensor1_w_lvl_1: 1,
    sensor1_w_lvl_2: 1.5,
    sensor1_w_lvl_3: 2
  }
]
```
