### ISSUE TITLE
Custom pagination controls

### ISSUE THREAD

**Issue by DBurrSudz** [kouts/vue-dataset#75]
Does this package support custom pagination controls and if yes, is there a guide on how to do it because the current docs do not explain this really well.

**Comment by kouts** [comment]
Hey @DBurrSudz, you can build a custom pagination controls component but leveraging the `injects` that `vue-dataset` [provides](https://next--vue-dataset-demo.netlify.app/components/#provides).
These will give you all the things you need to build your own pagination controls.

I have created a [CodeSandbox demonstrating a minimal custom pager](https://codesandbox.io/s/vue2-dataset-custom-pager-buzvq1?file=/src/components/Pager.vue), and I would also suggest to take a look at the source code of [DatasetPager](https://github.com/kouts/vue-dataset/blob/0559b1cfeccf9e05aa3bff7b16bb8da574058688/src/DatasetPager.vue) for ideas.

Let me know if that helped.

**Comment by DBurrSudz** [comment]
Thanks.
