### ISSUE TITLE
DatasetShow Component shows wrong number of shown entries on initial load

### ISSUE THREAD

**Issue by phillipmohr** [kouts/vue-dataset#79]
I'm using the the dataset-show component like this:
`<dataset-show :ds-show-entries="25" />`

It shows me 25 items per page, which is correct. But the selected options is 5, but it should be 25.

When changing the selected options to 50, I get 50 results and the text inside the select is 50, which is fully correct.

![Bildschirmfoto 2022-06-18 um 17 42 14](https://user-images.githubusercontent.com/30236221/174446086-0a339c57-369f-4c26-8871-7d4bf0b7b04b.png)
.

**Comment by kouts** [comment]
Hello @phillipmohr, you need to bind the `selected` number to a variable and listen to the `changed` event of the `dataset-show` component.
Check the [stackblitz here](https://stackblitz.com/edit/vue-tnwd27?file=src/App.vue).
