### ISSUE TITLE
can't register the component correctly

### ISSUE THREAD

**Issue by xiepu1212** [kouts/vue-dataset#87]
I imported all the components in main.js
![image](https://user-images.githubusercontent.com/34331649/181738856-a5fca0c6-65a7-4cf6-9a1d-50919ce98311.png)
but I still got an error prompt when I used them
![image](https://user-images.githubusercontent.com/34331649/181740106-53d8b048-a10f-44bf-86d1-2cf397800889.png)
What should I do?

**Comment by kouts** [comment]
Hello @xiepu1212 are you using Vue.js 3?

**Comment by xiepu1212** [comment]
> Hello @xiepu1212 are you using Vue.js 3?

vue2

**Comment by kouts** [comment]
Ok it might be something wrong with the release files, until I find some time to check you can try fixing the version to a lower number in you `package.json` e.g.
`"vue-dataset": "1.1.13"`

**Comment by xiepu1212** [comment]
> Ok it might be something wrong with the release files, until I find some time to check you can try fixing the version to a lower number in your `package.json` e.g. `"vue-dataset": "1.1.13"`

ok,thanks. I'll try it.

**Comment by kouts** [comment]
I've created a Codesandbox here and it seems everything is ok.
https://codesandbox.io/s/vue2-dataset-playground-standalone-pgn7x8?file=/src/App.vue
