### ISSUE TITLE
Clear the search input?

### ISSUE THREAD

**Issue by gerdsuhr** [kouts/vue-dataset#88]
Hi Kouts, How can I clear the search input with a click method?  I've tried this.search = '' and this.dsSearch = '' but neither seem to work.

**Comment by kouts** [comment]
Hey @gerdsuhr, I think you'll need a custom search component for that.
[Here's a Codesandbox](https://codesandbox.io/s/vue2-dataset-playground-custom-search-cojeu7?file=/src/App.vue) with an example of how you can do it.

Let me know if that helped.

**Comment by gerdsuhr** [comment]
I'm using vue 3. I tried using refs as well but no luck. Boss wont okay it for production unless we get the clear button to work on the search input. Really need your help. Thanks

**Comment by gerdsuhr** [comment]
I'm not able to get it functioning. Search is not working now.  Is the VUE 3 version? I'm on vue 3.

**Comment by kouts** [comment]
Here's a [Stackblitz](https://vue-amb1w1.stackblitz.io) with the Vue3 equivalent.

**Comment by gerdsuhr** [comment]
Giannis, Thank you so much!
