### ISSUE TITLE
What is the returned data object after I run a filter function?

### ISSUE THREAD

**Issue by gerdsuhr** [kouts/vue-dataset#95]
Hi, after I execute a filter function I need to use the returned (filtered) data object in another vue method.  Can you show example snippet of how this is done?  IE.. Using "ds-data" or "dsData" does not seem to work. What is the returned data object after filtering it?  
As an example, after running the filter function, in another method how do I console.log that filtered data set?

  Thanks

**Comment by kouts** [comment]
Hello @gerdsuhr, a feature that would return the data object through e.g an `event` is not available in `vue-dataset`.
I think it's something that's probably worth implementing in future releases.

**Comment by kouts** [comment]
There's now an `update:dsData` event that returns the filtered data.
@gerdsuhr you can check the example here https://github.com/kouts/vue-dataset/blob/6a37b323b62bbbc8aa4dbec872b98547c22cadc4/playground/views/Example2.vue#L16.
